### ISSUE TITLE
перенести классы в пакет

### ISSUE THREAD

**Issue by gochaorg** [pynchon-thomas/patroni-exporter#2]
https://github.com/pynchon-thomas/patroni-exporter/blob/48371bb481352085ab119800517d6471256fc9f2/src/main/java/App.java#L1

твои классы болтаются в корне /src/main/java

перенеси их в отдельный пакет, например ru.pynchon_thomas

```java
package ru.pynchon_thomas
```

должно быть что-то в духе

    /src/main/java/ru/pynchon_thomas/App.java
    /src/main/java/ru/pynchon_thomas/Metrics.java
    ...
    
[глянь вот это Naming Conventions](https://docs.oracle.com/javase/tutorial/java/package/namingpkgs.html)

**Comment by pynchon-thomas** [comment]
done -- packaged to org.fia
